/**
 * Common Components Barrel Export
 *
 * Re-exports Ant Design components with consistent naming for use throughout the application.
 * This module provides a centralized import point for UI components.
 *
 * Ant Design already provides Button, Table, Form, Modal, etc. with comprehensive
 * functionality, so we re-export them directly rather than creating wrapper components.
 */

// Re-export Ant Design components for consistent imports
export {
  Button,
  Table,
  Form,
  Modal,
  Input,
  Select,
  Checkbox,
  Radio,
  Switch,
  DatePicker,
  TimePicker,
  Upload,
  Progress,
  Spin,
  Alert,
  message,
  notification,
  Card,
  Collapse,
  Tabs,
  Tag,
  Badge,
  Tooltip,
  Popover,
  Popconfirm,
  Dropdown,
  Menu,
  Breadcrumb,
  Pagination,
  Steps,
  Divider,
  Space,
  Row,
  Col,
  Typography,
  Avatar,
  List,
  Descriptions,
  Empty,
  Result,
  Skeleton,
  Image,
  Statistic,
  Tree,
  TreeSelect,
  Transfer,
  Cascader,
  AutoComplete,
  Rate,
  Slider,
  InputNumber,
  ColorPicker,
  Segmented,
  Flex,
  Watermark,
  ConfigProvider,
  theme,
  App,
  Layout,
  Drawer,
  Affix,
  Anchor,
  BackTop,
  FloatButton,
  Timeline,
  Calendar,
  QRCode,
  Tour,
} from 'antd';

// Re-export component types
export type {
  ButtonProps,
  TableProps,
  FormProps,
  ModalProps,
  InputProps,
  SelectProps,
  CheckboxProps,
  RadioProps,
  SwitchProps,
  UploadProps,
  ProgressProps,
  SpinProps,
  AlertProps,
  CardProps,
  CollapseProps,
  TabsProps,
  TagProps,
  BadgeProps,
  TooltipProps,
  PopoverProps,
  PopconfirmProps,
  DropdownProps,
  MenuProps,
  BreadcrumbProps,
  PaginationProps,
  StepsProps,
  DividerProps,
  SpaceProps,
  RowProps,
  ColProps,
  AvatarProps,
  ListProps,
  DescriptionsProps,
  EmptyProps,
  ResultProps,
  SkeletonProps,
  ImageProps,
  StatisticProps,
  TreeProps,
  TreeSelectProps,
  TransferProps,
  CascaderProps,
  AutoCompleteProps,
  RateProps,
  SliderProps,
  InputNumberProps,
  SegmentedProps,
  FlexProps,
  WatermarkProps,
  ConfigProviderProps,
  LayoutProps,
  DrawerProps,
  AffixProps,
  AnchorProps,
  FloatButtonProps,
  TimelineProps,
  CalendarProps,
  QRCodeProps,
  TourProps,
} from 'antd';

// Export custom components
export { default as FileUpload } from './FileUpload';
export type { FileUploadProps } from './FileUpload';
