import React from 'react';
import {
  SiApachemaven,
  SiGradle,
  SiNpm,
  SiPython,
  SiNuget,
  SiGo,
  SiRubygems,
  SiDocker,
  SiHelm,
  SiRedhat,
  SiDebian,
  SiCplusplus,
  SiRust,
  SiPodman,
  SiWebassembly,
  SiPoetry,
  SiAnaconda,
  SiYarn,
  SiBower,
  SiPnpm,
  SiChocolatey,
  SiDotnet,
  SiTerraform,
  SiOpentofu,
  SiAlpinelinux,
  SiComposer,
  SiElixir,
  SiCocoapods,
  SiSwift,
  SiDart,
  SiScala,
  SiChef,
  SiPuppet,
  SiAnsible,
  SiGit,
  SiVscodium,
  SiJetbrains,
  SiHuggingface,
  SiR,
  SiVagrant,
  SiLinux,
  SiEclipseide,
  SiBazel,
} from '@icons-pack/react-simple-icons';
import { FileOutlined } from '@ant-design/icons';

/**
 * Brand colors for each package format.
 */
export const formatBrandColors: Record<string, string> = {
  maven: '#C71A36',
  gradle: '#02303A',
  npm: '#CB3837',
  pypi: '#3776AB',
  nuget: '#004880',
  go: '#00ADD8',
  rubygems: '#E9573F',
  docker: '#2496ED',
  helm: '#0F1689',
  rpm: '#EE0000',
  debian: '#A81D33',
  conan: '#00599C',
  cargo: '#DEA584',
  generic: '#8C8C8C',
  podman: '#892CA0',
  buildx: '#2496ED',
  oras: '#2496ED',
  wasm_oci: '#654FF0',
  helm_oci: '#0F1689',
  poetry: '#60A5FA',
  conda: '#44A833',
  yarn: '#2C8EBB',
  bower: '#EF5734',
  pnpm: '#F69220',
  chocolatey: '#80B5E3',
  powershell: '#512BD4',
  terraform: '#7B42BC',
  opentofu: '#FFDA18',
  alpine: '#0D597F',
  conda_native: '#44A833',
  composer: '#885630',
  hex: '#4B275F',
  cocoapods: '#EE3322',
  swift: '#F05138',
  pub: '#0175C2',
  sbt: '#DC322F',
  chef: '#F09820',
  puppet: '#FFAE1A',
  ansible: '#EE0000',
  gitlfs: '#F05032',
  vscode: '#2F80ED',
  jetbrains: '#000000',
  huggingface: '#FFD21E',
  mlmodel: '#FFD21E',
  cran: '#276DC3',
  vagrant: '#1868F2',
  opkg: '#FCC624',
  p2: '#2C2255',
  bazel: '#43A047',
};

type IconComponent = React.ComponentType<{ size?: number; color?: string }>;

const formatIconComponents: Record<string, IconComponent> = {
  maven: SiApachemaven,
  gradle: SiGradle,
  npm: SiNpm,
  pypi: SiPython,
  nuget: SiNuget,
  go: SiGo,
  rubygems: SiRubygems,
  docker: SiDocker,
  helm: SiHelm,
  rpm: SiRedhat,
  debian: SiDebian,
  conan: SiCplusplus,
  cargo: SiRust,
  podman: SiPodman,
  buildx: SiDocker,
  oras: SiDocker,
  wasm_oci: SiWebassembly,
  helm_oci: SiHelm,
  poetry: SiPoetry,
  conda: SiAnaconda,
  yarn: SiYarn,
  bower: SiBower,
  pnpm: SiPnpm,
  chocolatey: SiChocolatey,
  powershell: SiDotnet,
  terraform: SiTerraform,
  opentofu: SiOpentofu,
  alpine: SiAlpinelinux,
  conda_native: SiAnaconda,
  composer: SiComposer,
  hex: SiElixir,
  cocoapods: SiCocoapods,
  swift: SiSwift,
  pub: SiDart,
  sbt: SiScala,
  chef: SiChef,
  puppet: SiPuppet,
  ansible: SiAnsible,
  gitlfs: SiGit,
  vscode: SiVscodium,
  jetbrains: SiJetbrains,
  huggingface: SiHuggingface,
  mlmodel: SiHuggingface,
  cran: SiR,
  vagrant: SiVagrant,
  opkg: SiLinux,
  p2: SiEclipseide,
  bazel: SiBazel,
};

/**
 * Get a format icon as a React element.
 *
 * Uses Simple Icons brand SVGs where available, falls back to
 * Ant Design's FileOutlined for unknown formats.
 *
 * @param format - The repository/package format key
 * @param size - Icon size in pixels (default 20)
 * @param color - Override color (defaults to brand color)
 */
export function getFormatIcon(
  format: string,
  size: number = 20,
  color?: string,
): React.ReactNode {
  const Component = formatIconComponents[format];
  if (Component) {
    return <Component size={size} color={color ?? formatBrandColors[format]} />;
  }
  return <FileOutlined style={{ fontSize: size, color: color ?? '#8C8C8C' }} />;
}
