import type { PackageType } from '../types';

/**
 * Human-readable labels for package types.
 */
export const packageTypeLabels: Record<PackageType, string> = {
  maven: 'Maven',
  gradle: 'Gradle',
  npm: 'npm',
  pypi: 'PyPI',
  nuget: 'NuGet',
  go: 'Go',
  rubygems: 'RubyGems',
  docker: 'Docker',
  helm: 'Helm',
  rpm: 'RPM',
  debian: 'Debian',
  conan: 'Conan',
  cargo: 'Cargo',
  generic: 'Generic',
  podman: 'Podman',
  buildx: 'BuildX',
  oras: 'ORAS',
  wasm_oci: 'WASM (OCI)',
  helm_oci: 'Helm OCI',
  poetry: 'Poetry',
  conda: 'Conda',
  yarn: 'Yarn',
  bower: 'Bower',
  pnpm: 'pnpm',
  chocolatey: 'Chocolatey',
  powershell: 'PowerShell',
  terraform: 'Terraform',
  opentofu: 'OpenTofu',
  alpine: 'Alpine APK',
  conda_native: 'Conda',
  composer: 'Composer',
  hex: 'Hex',
  cocoapods: 'CocoaPods',
  swift: 'Swift',
  pub: 'Pub (Dart)',
  sbt: 'sbt/Ivy',
  chef: 'Chef',
  puppet: 'Puppet',
  ansible: 'Ansible',
  gitlfs: 'Git LFS',
  vscode: 'VS Code Extensions',
  jetbrains: 'JetBrains Plugins',
  huggingface: 'Hugging Face',
  mlmodel: 'ML Models',
  cran: 'CRAN (R)',
  vagrant: 'Vagrant',
  opkg: 'Opkg',
  p2: 'P2 (Eclipse)',
  bazel: 'Bazel',
};
